// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSBhBdYGDbodzw8Od9BrNX6-ocP78t3c',
    appId: '1:332376083539:web:b1fca814bb34db4f484aa6',
    messagingSenderId: '332376083539',
    projectId: 'loann-2e6ee',
    authDomain: 'loann-2e6ee.firebaseapp.com',
    storageBucket: 'loann-2e6ee.firebasestorage.app',
    measurementId: 'G-79TL5X1QXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgNQmH1S_JwLMGZiEBX6l_T4idRhfj_E',
    appId: '1:332376083539:android:6918b4c93e03f144484aa6',
    messagingSenderId: '332376083539',
    projectId: 'loann-2e6ee',
    storageBucket: 'loann-2e6ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATpcblLUtNQEknjK8i-HaaRrXUjGGzJp4',
    appId: '1:332376083539:ios:2fb203aa9ec3fe63484aa6',
    messagingSenderId: '332376083539',
    projectId: 'loann-2e6ee',
    storageBucket: 'loann-2e6ee.firebasestorage.app',
    androidClientId: '332376083539-qs2hokuca4vcalt2qv8caibak4kqklup.apps.googleusercontent.com',
    iosClientId: '332376083539-lu7349aul3dnjoatpab88iq9f9sm7om2.apps.googleusercontent.com',
    iosBundleId: 'com.loanservice.loanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpcblLUtNQEknjK8i-HaaRrXUjGGzJp4',
    appId: '1:332376083539:ios:2fb203aa9ec3fe63484aa6',
    messagingSenderId: '332376083539',
    projectId: 'loann-2e6ee',
    storageBucket: 'loann-2e6ee.firebasestorage.app',
    androidClientId: '332376083539-qs2hokuca4vcalt2qv8caibak4kqklup.apps.googleusercontent.com',
    iosClientId: '332376083539-lu7349aul3dnjoatpab88iq9f9sm7om2.apps.googleusercontent.com',
    iosBundleId: 'com.loanservice.loanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfSBhBdYGDbodzw8Od9BrNX6-ocP78t3c',
    appId: '1:332376083539:web:55462d04055dbbe9484aa6',
    messagingSenderId: '332376083539',
    projectId: 'loann-2e6ee',
    authDomain: 'loann-2e6ee.firebaseapp.com',
    storageBucket: 'loann-2e6ee.firebasestorage.app',
    measurementId: 'G-SMTFFEDR9Q',
  );

}